extern ShortMove shortmove_100;
extern ShortMove shortmove_2;
extern ShortMove shortmove_202;
extern ShortMove shortmove_207;
extern ShortMove shortmove_250;
extern ShortMove shortmove_252;
extern ShortMove shortmove_255;
extern ShortMove shortmove_257;
extern ShortMove shortmove_400;
extern ShortMove shortmove_5;
extern ShortMove shortmove_50;
extern ShortMove shortmove_500;
extern ShortMove shortmove_502;
extern ShortMove shortmove_505;
extern ShortMove shortmove_507;
extern ShortMove shortmove_52;
extern ShortMove shortmove_55;
extern ShortMove shortmove_550;
extern ShortMove shortmove_557;
extern ShortMove shortmove_57;
extern ShortMove shortmove_7;
extern ShortMove shortmove_705;
extern ShortMove shortmove_707;
extern ShortMove shortmove_757;
extern ShortMove shortmove_777;

extern LongMove longmove_102;
extern LongMove longmove_2;
extern LongMove longmove_200;
extern LongMove longmove_202;
extern LongMove longmove_205;
extern LongMove longmove_252;
extern LongMove longmove_402;
extern LongMove longmove_50;
extern LongMove longmove_500;
extern LongMove longmove_502;
extern LongMove longmove_505;
extern LongMove longmove_52;
extern LongMove longmove_707;

extern JumpMove jumpmove_2;
extern JumpMove jumpmove_205;
extern JumpMove jumpmove_707;

extern NumMove nummove_200_2;
extern NumMove nummove_500_2;
extern NumMove nummove_5_3;

extern KnightMove knightmove_2;
extern KnightMove knightmove_202;

