ShortMove shortmove_100(0x100);
ShortMove shortmove_2(0x2);
ShortMove shortmove_202(0x202);
ShortMove shortmove_207(0x207);
ShortMove shortmove_250(0x250);
ShortMove shortmove_252(0x252);
ShortMove shortmove_255(0x255);
ShortMove shortmove_257(0x257);
ShortMove shortmove_400(0x400);
ShortMove shortmove_5(0x5);
ShortMove shortmove_50(0x50);
ShortMove shortmove_500(0x500);
ShortMove shortmove_502(0x502);
ShortMove shortmove_505(0x505);
ShortMove shortmove_507(0x507);
ShortMove shortmove_52(0x52);
ShortMove shortmove_55(0x55);
ShortMove shortmove_550(0x550);
ShortMove shortmove_557(0x557);
ShortMove shortmove_57(0x57);
ShortMove shortmove_7(0x7);
ShortMove shortmove_705(0x705);
ShortMove shortmove_707(0x707);
ShortMove shortmove_757(0x757);
ShortMove shortmove_777(0x777);

LongMove longmove_102(0x102);
LongMove longmove_2(0x2);
LongMove longmove_200(0x200);
LongMove longmove_202(0x202);
LongMove longmove_205(0x205);
LongMove longmove_252(0x252);
LongMove longmove_402(0x402);
LongMove longmove_50(0x50);
LongMove longmove_500(0x500);
LongMove longmove_502(0x502);
LongMove longmove_505(0x505);
LongMove longmove_52(0x52);
LongMove longmove_707(0x707);

JumpMove jumpmove_2(0x2);
JumpMove jumpmove_205(0x205);
JumpMove jumpmove_707(0x707);

NumMove nummove_200_2(0x200, 0x2);
NumMove nummove_500_2(0x500, 0x2);
NumMove nummove_5_3(0x5, 0x3);

KnightMove knightmove_2(0x2);
KnightMove knightmove_202(0x202);

