# Makefile.gnu [bof] (c) Igor Durdanovic

NAME = GDK

include ../../config/opts.c++

CC_DEFS =
CC_ARGS =  $(CC_FLAGS) $(CC_DEFS) $(CC_INCS)

include ../../config/opts.lib.rules

# Makefile.gnu [eof] (c) Igor Durdanovic
