# Makefile.gnu [bof] (c) Igor Durdanovic

MAIN = td

CC_INCS = -I../GDK/src
LD_ARGS = -L../GDK/lib
LD_LIBS = -lGDK

include ../../config/opts.c++

CC_DEFS =
CC_ARGS = $(CC_FLAGS) $(CC_DEFS) $(CC_INCS)

include ../../config/opts.bin.rules

# Makefile.gnu [eof] (c) Igor Durdanovic
