# Makefile.gnu [bof] (c) Igor Durdanovic

MAIN = Multiplexor

include ../../config/opts.c++

CC_DEFS = -DLOG=2 -DLOG_ERR -DMULTIPLEXER $(LIB_DEF) -DDIR=$CWD
CC_ARGS = $(CC_FLAGS) $(CC_DEFS) $(CC_INCS)

include ../../config/opts.bin.rules

# Makefile.gnu [eof] (c) Igor Durdanovic
